# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: turborex 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "turborex".freeze
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["exist".freeze]
  s.date = "2020-10-30"
  s.description = "This gem is mainly a proof of concept for the topic \"Automated Hunting for Cross-Server Xrefs in Microsoft RPC and COM\" on Code Blue 2020. It is a locator for RPC server/client routines and COM interface methods/client calls, so it can be used to search for Cross-Server Xrefs scenes. In addition, it also has other functions such as ALPC client/server.".freeze
  s.email = "exist_sycsec@outlook.com".freeze
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md",
    "README.rdoc"
  ]
  s.files = [
    "examples/alpc_client.rb",
    "examples/alpc_server.rb",
    "examples/com_client.rb",
    "examples/com_finder.rb",
    "examples/create_instance.rb",
    "examples/cstruct.rb",
    "examples/find_com_client_calls.rb",
    "examples/find_rpc_security_callback.rb",
    "examples/rpc_finder.rb",
    "examples/scan_exports.rb",
    "examples/scan_imports.rb",
    "examples/tinysdk.rb",
    "lib/turborex.rb",
    "lib/turborex/cstruct.rb",
    "lib/turborex/cstruct/struct_helper.rb",
    "lib/turborex/exception.rb",
    "lib/turborex/fuzzer.rb",
    "lib/turborex/fuzzer/containers.rb",
    "lib/turborex/fuzzer/coverage.rb",
    "lib/turborex/fuzzer/mutators.rb",
    "lib/turborex/fuzzer/seed.rb",
    "lib/turborex/monkey.rb",
    "lib/turborex/msrpc.rb",
    "lib/turborex/msrpc/decompiler.rb",
    "lib/turborex/msrpc/midl.rb",
    "lib/turborex/msrpc/ndrtype.rb",
    "lib/turborex/msrpc/rpcbase.rb",
    "lib/turborex/msrpc/rpcfinder.rb",
    "lib/turborex/msrpc/utils.rb",
    "lib/turborex/pefile.rb",
    "lib/turborex/pefile/pe.rb",
    "lib/turborex/pefile/scanner.rb",
    "lib/turborex/utils.rb",
    "lib/turborex/windows.rb",
    "lib/turborex/windows/alpc.rb",
    "lib/turborex/windows/com.rb",
    "lib/turborex/windows/com/client.rb",
    "lib/turborex/windows/com/com_finder.rb",
    "lib/turborex/windows/com/com_registry.rb",
    "lib/turborex/windows/com/interface.rb",
    "lib/turborex/windows/com/utils.rb",
    "lib/turborex/windows/constants.rb",
    "lib/turborex/windows/process.rb",
    "lib/turborex/windows/security.rb",
    "lib/turborex/windows/security/ace.rb",
    "lib/turborex/windows/security/acl.rb",
    "lib/turborex/windows/security/security_descriptor.rb",
    "lib/turborex/windows/tinysdk.rb",
    "lib/turborex/windows/utils.rb",
    "resources/headers/alpc/ntdef.h",
    "resources/headers/alpc/ntlpcapi.h",
    "resources/headers/rpc/common.h",
    "resources/headers/rpc/guiddef.h",
    "resources/headers/rpc/internal_ndrtypes.h",
    "resources/headers/rpc/rpc.h",
    "resources/headers/rpc/rpcdce.h",
    "resources/headers/rpc/rpcdcep.h",
    "resources/headers/rpc/rpcndr.h",
    "resources/headers/rpc/v4_x64/rpcinternals.h",
    "resources/headers/rpc/wintype.h",
    "resources/headers/tinysdk/tinysdk.h",
    "resources/headers/tinysdk/tinysdk/comdef.h",
    "resources/headers/tinysdk/tinysdk/dbghelp.h",
    "resources/headers/tinysdk/tinysdk/guiddef.h",
    "resources/headers/tinysdk/tinysdk/memoryapi.h",
    "resources/headers/tinysdk/tinysdk/poppack.h",
    "resources/headers/tinysdk/tinysdk/pshpack4.h",
    "resources/headers/tinysdk/tinysdk/winnt.h",
    "resources/headers/tinysdk/tinysdk/wintype.h"
  ]
  s.homepage = "http://github.com/existXFx/turborex".freeze
  s.licenses = ["GPLv3".freeze]
  s.rubygems_version = "2.6.14.4".freeze
  s.summary = "A toolkit for exploring and exploiting MSRPC and COM.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rex>.freeze, ["~> 2.0.11"])
      s.add_runtime_dependency(%q<docile>.freeze, ["~> 1.3.2"])
      s.add_runtime_dependency(%q<rgl>.freeze, ["~> 0.5.6"])
      s.add_runtime_dependency(%q<win32-api>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<os>.freeze, [">= 0"])
      s.add_development_dependency(%q<shoulda>.freeze, [">= 0"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>.freeze, [">= 0"])
      s.add_development_dependency(%q<juwelier>.freeze, [">= 0"])
      s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
      s.add_development_dependency(%q<pry-byebug>.freeze, [">= 0"])
      s.add_development_dependency(%q<rspec>.freeze, [">= 0"])
    else
      s.add_dependency(%q<rex>.freeze, ["~> 2.0.11"])
      s.add_dependency(%q<docile>.freeze, ["~> 1.3.2"])
      s.add_dependency(%q<rgl>.freeze, ["~> 0.5.6"])
      s.add_dependency(%q<win32-api>.freeze, [">= 0"])
      s.add_dependency(%q<os>.freeze, [">= 0"])
      s.add_dependency(%q<shoulda>.freeze, [">= 0"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_dependency(%q<bundler>.freeze, [">= 0"])
      s.add_dependency(%q<juwelier>.freeze, [">= 0"])
      s.add_dependency(%q<simplecov>.freeze, [">= 0"])
      s.add_dependency(%q<pry-byebug>.freeze, [">= 0"])
      s.add_dependency(%q<rspec>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<rex>.freeze, ["~> 2.0.11"])
    s.add_dependency(%q<docile>.freeze, ["~> 1.3.2"])
    s.add_dependency(%q<rgl>.freeze, ["~> 0.5.6"])
    s.add_dependency(%q<win32-api>.freeze, [">= 0"])
    s.add_dependency(%q<os>.freeze, [">= 0"])
    s.add_dependency(%q<shoulda>.freeze, [">= 0"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_dependency(%q<bundler>.freeze, [">= 0"])
    s.add_dependency(%q<juwelier>.freeze, [">= 0"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    s.add_dependency(%q<pry-byebug>.freeze, [">= 0"])
    s.add_dependency(%q<rspec>.freeze, [">= 0"])
  end
end

